package commands

import (
	"fmt"

	"github.com/latere-ai/latere-cli/internal/upgrade"
	"github.com/spf13/cobra"
)

// NewRoot builds the full command tree. Version is injected from main.
//
// The root command is product-neutral: each Latere product gets its own
// subcommand group under this binary (sandbox today; more to follow).
func NewRoot(version string) *cobra.Command {
	root := &cobra.Command{
		Use:   "latere",
		Short: "Command-line interface for the Latere product family.",
		Long: `latere is a single binary for interacting with Latere services from the terminal.
See https://latere.ai for the product family.

Start with 'latere auth login', then use 'latere cella' to create,
list, run commands in, and move files in or out of Cella workspaces.

Shell completion is generated by this binary. Run 'latere completion
<shell>' to print the script for bash, zsh, fish, or powershell, then
load it from your shell startup files.`,
		Example: `  latere auth login
  latere cella list
  latere cella apply -f sandbox.yaml
  latere cella shell dev
  latere completion zsh`,
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.Version = version
	root.SetVersionTemplate("latere {{.Version}}\n")
	root.CompletionOptions.DisableDefaultCmd = true

	// Passive release awareness: before any command (except the
	// release-management ones), serve an update notice from the cached
	// check and, if the user opted in, auto-upgrade. Best-effort and
	// non-fatal — it never blocks the command being run.
	root.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if !skipUpdateCheck(cmd) {
			upgrade.OnStart(version, cmd.ErrOrStderr())
		}
		return nil
	}

	root.AddCommand(newAuthCmd())
	root.AddCommand(newCellaCmd())
	root.AddCommand(newToposCmd())
	root.AddCommand(newLuxCmd())
	root.AddCommand(newUpgradeCmd(version))
	root.AddCommand(newCompletionCmd(root))
	return root
}

// skipUpdateCheck reports whether the passive update check should be skipped
// for cmd. The upgrade command does its own checking; completion and help
// output must stay clean and machine-parseable.
func skipUpdateCheck(cmd *cobra.Command) bool {
	for c := cmd; c != nil; c = c.Parent() {
		switch c.Name() {
		case "upgrade", "completion", "help", "__complete", "__completeNoDesc":
			return true
		}
	}
	return false
}

func newCompletionCmd(root *cobra.Command) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "completion <bash|zsh|fish|powershell>",
		Short: "Generate shell completion for latere.",
		Long: `Generate a shell completion script for latere.

Completion lets your shell suggest Latere commands, subcommands, and
flags when you press Tab. Print the script for your shell, then source
it from your shell startup file or install it into your shell's
completion directory.`,
		Example: `  mkdir -p ~/.zsh/completions
  latere completion zsh > ~/.zsh/completions/_latere
  echo 'fpath=(~/.zsh/completions $fpath)' >> ~/.zshrc
  echo 'autoload -Uz compinit && compinit' >> ~/.zshrc

  mkdir -p ~/.local/share/bash-completion/completions
  latere completion bash > ~/.local/share/bash-completion/completions/latere
  mkdir -p ~/.config/fish/completions
  latere completion fish > ~/.config/fish/completions/latere.fish
  latere completion powershell > latere.ps1`,
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh", "fish", "powershell"},
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()
			switch args[0] {
			case "bash":
				return root.GenBashCompletion(out)
			case "zsh":
				return root.GenZshCompletion(out)
			case "fish":
				return root.GenFishCompletion(out, true)
			case "powershell":
				return root.GenPowerShellCompletion(out)
			default:
				return fmt.Errorf("unsupported shell %q; expected bash, zsh, fish, or powershell", args[0])
			}
		},
	}
	return cmd
}
