// SPDX-FileCopyrightText: 2026 Latere AI
// SPDX-License-Identifier: MIT

package commands

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/latere-ai/latere-cli/internal/upgrade"
)

// NewRoot builds the full command tree. Version is injected from main.
//
// The root command is the platform's: each capability is a command group
// named after it (spec 011), and the session verbs sit at the top level.
func NewRoot(version string) *cobra.Command {
	root := &cobra.Command{
		Use:   "latere",
		Short: "Command-line interface for the Latere platform.",
		Long: `latere is the command line of the Latere platform. See https://latere.ai.

Start with 'latere login'. Then 'latere models' lists and calls models,
'latere environments' creates workloads, runs commands in them and moves
files in or out, 'latere agents run' runs the Latere agent on this machine,
'latere repos' creates Git repositories on Latere Code, and 'latere apps'
creates apps and follows their builds.

Shell completion is generated by this binary. Run 'latere completion
<shell>' to print the script for bash, zsh, fish, or powershell, then
load it from your shell startup files.`,
		Example: `  latere login
  latere environments list
  latere environments apply -f workload.yaml
  latere environments shell dev
  latere agents run
  latere repos create alice/notes
  latere apps create hello
  latere completion zsh`,
		SilenceUsage:  true,
		SilenceErrors: true,
	}
	root.Version = version
	root.SetVersionTemplate("latere {{.Version}}\n")
	root.CompletionOptions.DisableDefaultCmd = true

	// Passive release awareness: before any command (except the
	// release-management ones), serve an update notice from the cached
	// check and, if the user opted in, auto-upgrade. Best-effort and
	// non-fatal — it never blocks the command being run.
	root.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if !skipUpdateCheck(cmd) {
			upgrade.OnStart(version, cmd.ErrOrStderr())
		}
		return nil
	}

	// Session verbs live at the top level; `auth` stays as a hidden
	// back-compat alias built from the same factories.
	root.AddCommand(newAuthLoginCmd())
	root.AddCommand(newAuthWhoamiCmd())
	root.AddCommand(newAuthPrintTokenCmd())
	root.AddCommand(newAuthLogoutCmd())
	root.AddCommand(newOrgCmd())
	root.AddCommand(newAuthCmd())
	root.AddCommand(newGitCredentialCmd())
	root.AddCommand(newEnvironmentsCmd())
	root.AddCommand(newAgentsCmd())
	root.AddCommand(newEvalCmd())
	root.AddCommand(newModelsCmd())
	root.AddCommand(newReposCmd())
	root.AddCommand(newAppCmd())
	for word := range retiredCommands {
		root.AddCommand(newRetiredCmd(word))
	}
	root.AddCommand(newUpgradeCmd(version))
	root.AddCommand(newCompletionCmd(root))
	return root
}

// skipUpdateCheck reports whether the passive update check should be skipped
// for cmd. The upgrade command does its own checking; completion and help
// output must stay clean and machine-parseable; git-credential is invoked by
// git on every fetch/push, so a notice on stderr (or an in-place
// auto-upgrade) must never interleave with the credential protocol;
// print-token feeds command substitution and must stay clean the same way.
func skipUpdateCheck(cmd *cobra.Command) bool {
	for c := cmd; c != nil; c = c.Parent() {
		switch c.Name() {
		case "upgrade", "completion", "help", "__complete", "__completeNoDesc", "git-credential", "print-token":
			return true
		}
	}
	return false
}

func newCompletionCmd(root *cobra.Command) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "completion <bash|zsh|fish|powershell>",
		Short: "Generate shell completion for latere.",
		Long: `Generate a shell completion script for latere.

Completion lets your shell suggest Latere commands, subcommands, and
flags when you press Tab. Print the script for your shell, then source
it from your shell startup file or install it into your shell's
completion directory.`,
		Example: `  mkdir -p ~/.zsh/completions
  latere completion zsh > ~/.zsh/completions/_latere
  echo 'fpath=(~/.zsh/completions $fpath)' >> ~/.zshrc
  echo 'autoload -Uz compinit && compinit' >> ~/.zshrc

  mkdir -p ~/.local/share/bash-completion/completions
  latere completion bash > ~/.local/share/bash-completion/completions/latere
  mkdir -p ~/.config/fish/completions
  latere completion fish > ~/.config/fish/completions/latere.fish
  latere completion powershell > latere.ps1`,
		Args:      cobra.ExactArgs(1),
		ValidArgs: []string{"bash", "zsh", "fish", "powershell"},
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()
			switch args[0] {
			case "bash":
				return root.GenBashCompletion(out)
			case "zsh":
				return root.GenZshCompletion(out)
			case "fish":
				return root.GenFishCompletion(out, true)
			case "powershell":
				return root.GenPowerShellCompletion(out)
			default:
				return fmt.Errorf("unsupported shell %q; expected bash, zsh, fish, or powershell", args[0])
			}
		},
	}
	return cmd
}
